//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace importService_Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class blood_services_
    {
        public int ID { get; set; }
        public Nullable<double> blood { get; set; }
        public Nullable<double> service { get; set; }
        public Nullable<double> result { get; set; }
        public Nullable<double> finished { get; set; }
        public string accepted { get; set; }
        public string status { get; set; }
        public string analyzer { get; set; }
        public Nullable<double> user { get; set; }
    }
}
