//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace importService_Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blood_Service
    {
        public int ID { get; set; }
        public Nullable<int> IBlood { get; set; }
        public Nullable<int> IService { get; set; }
        public double Result { get; set; }
        public bool IsAccepted { get; set; }
        public Nullable<int> IStatus { get; set; }
        public Nullable<int> IAnalyzer { get; set; }
        public Nullable<int> IUser { get; set; }
    
        public virtual Blood Blood { get; set; }
        public virtual Blood_Analyzer Blood_Analyzer { get; set; }
        public virtual Service Service { get; set; }
        public virtual Blood_Status Blood_Status { get; set; }
        public virtual User User { get; set; }
    }
}
