//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace importService_Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login_History
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public Nullable<int> IPatient { get; set; }
        public string IPaddress { get; set; }
        public string Browser { get; set; }
        public string UA { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
