//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace importService_Client
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Docstation : DbContext
    {
        public Docstation()
            : base("name=Docstation")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<patients_> patients_ { get; set; }
        public virtual DbSet<services_> services_ { get; set; }
        public virtual DbSet<users_> users_ { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Insurance> Insurances { get; set; }
        public virtual DbSet<Login_History> Login_History { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<Social_License> Social_License { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<User_Patient> User_Patient { get; set; }
        public virtual DbSet<User_Service> User_Service { get; set; }
        public virtual DbSet<User_Type> User_Type { get; set; }
    }
}
