//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace importService_Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class patients_
    {
        public int ID { get; set; }
        public string fullname { get; set; }
        public string login { get; set; }
        public string pwd { get; set; }
        public string guid { get; set; }
        public string email { get; set; }
        public Nullable<double> social_sec_number { get; set; }
        public string ein { get; set; }
        public string social_type { get; set; }
        public string phone { get; set; }
        public Nullable<double> passport_s { get; set; }
        public Nullable<double> passport_n { get; set; }
        public Nullable<double> birthdate_timestamp { get; set; }
        public string country { get; set; }
        public string insurance_name { get; set; }
        public string insurance_address { get; set; }
        public Nullable<double> insurance_inn { get; set; }
        public Nullable<double> insurance_p { get; set; }
        public Nullable<double> insurance_bik { get; set; }
        public string ipadress2 { get; set; }
        public string ua { get; set; }
    }
}
