//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace importService_Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class service_client_
    {
        public int ID { get; set; }
        public string Услуга { get; set; }
        public Nullable<System.DateTime> Начало_оказания_услуги { get; set; }
        public string Клиент { get; set; }
    }
}
